### ISSUE TITLE
Skidding

### ISSUE THREAD

**Issue by HybridLeaksFN** [AtlasFn/backend-launcher#3]
Why you skidding neonite for 
hope u enjoy ur DCMA 

i'll just go and tell kemo now :)

**Comment by vinzyYT** [comment]
this is not a skid, this is a hybrid server of aurora and neonite

**Comment by HybridLeaksFN** [comment]
so a skid then lmao

**Comment by AlexDev404** [comment]
no it is not

**Comment by Beat-YT** [comment]
YES IT IS LMFAO

**Comment by HybridFNBR** [comment]
bunch of clowns you lot are
grow a brain

**Comment by AlexDev404** [comment]
Mhmm. I think we did already. Not sure about @Beat-YT since he doesn't know how to code. You can check out our new project on https://GitHub.com/trail-blaze/dyna-core-beta if you'd like.
