### ISSUE TITLE
Omg, Big Skid

### ISSUE THREAD

**Issue by Beat-YT** [AtlasFn/backend-launcher#5]
Verry big skid

**Comment by Nom-Youtube** [comment]
omg i ddiiddnntt rreeaalliizzee

**Comment by vinzyYT** [comment]
this project has been shutdown @Beat-YT @Nom-Youtube

**Comment by Beat-YT** [comment]
k, Still a  big big skid

**Comment by Beat-YT** [comment]
You can fix this using #6

**Comment by AlexDev404** [comment]
@Nom-Youtube @Beat-YT Stop being such a kid, delete your GitHub account, and come back when you've grown up enough

**Comment by Beat-YT** [comment]
LMFAO, YOU SHOULD DELETE IT , SKIDDING IS BAD, REALLY REALLY BAD, TAKING NEONITE AND CALL IT YOUR OWN IS SKIDDING SO STOP COMPLAINING.  GO CRY TO YOUR MOM AND DELETE YOUR GITUHB ACCOUNT

**Comment by Beat-YT** [comment]
Idiot

**Comment by AlexDev404** [comment]
> LMFAO, YOU SHOULD DELETE IT , SKIDDING IS BAD, REALLY REALLY BAD, TAKING NEONITE AND CALL IT YOUR OWN IS SKIDDING SO STOP COMPLAINING. GO CRY TO YOUR MOM AND DELETE YOUR GITUHB ACCOUNT

It is here for archival, legacy and other reasons. It is an important part of Blaze's history. Also, it is here to prevent link rot.

**Comment by AlexDev404** [comment]
I also still use the project timeline.
